### ISSUE TITLE
Character not facing right orientation all the time

### ISSUE THREAD

**Issue by slichtenheld** [OOP-Team-Project/RPG-Iteration-2#13]
If the character is facing down, and then the player attempts to move right or left, the player orientation stays down. Also if the character is facing right or left, and then the player attempts to face the opposite direction, the characters orientation doesn't change.

**Comment by JoshNassar94** [comment]
The character shouldn't be able to face right or left. The specs for movement for Iteration 2 are as follows: 
![image](https://cloud.githubusercontent.com/assets/10493696/13379291/b234fb22-ddef-11e5-986b-96b7179cc356.png)

As the picture shows, no horizontal movement. The only reason you can move that way now is because of the arrow keys. Once it's implemented on the numpad, you won't be able to.

**Comment by slichtenheld** [comment]
Totally forgot to close this after you explained it on slack, my bad
